// types product
export const GET_PRODUCT_FULLFILLED = 'GET_PRODUCT_FULLFILLED';
export const GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING';
export const GET_PRODUCT_REJECTED = 'GET_PRODUCT_REJECTED';

export const POST_PRODUCT_FULLFILLED = 'POST_PRODUCT_FULLFILLED';
export const POST_PRODUCT_PENDING = 'POST_PRODUCT_PENDING';
export const POST_PRODUCT_REJECTED = 'POST_PRODUCT_REJECTED';

export const DELETE_PRODUCT_FULLFILLED = 'DELETE_PRODUCT_FULLFILLED';
export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING';
export const DELETE_PRODUCT_REJECTED = 'DELETE_PRODUCT_REJECTED';
export const DELETE_GET_PRODUCT = 'DELETE_GET_PRODUCT';

export const UPDATE_PRODUCT_FULLFILLED = 'UPDATE_PRODUCT_FULLFILLED';
export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING';
export const UPDATE_PRODUCT_REJECTED = 'UPDATE_PRODUCT_REJECTED';
export const UPDATE_GET_PRODUCT = 'UPDATE_GET_PRODUCT';

export const POST_COMMENT_FULLFILLED = 'POST_COMMENT_FULLFILLED';
export const POST_COMMENT_PENDING = 'POST_COMMENT_PENDING';
export const POST_COMMENT_REJECTED = 'POST_COMMENT_REJECTED';

export const UPDATE_PRODUCT_PURCHASED_FULLFILLED = 'UPDATE_PRODUCT_PURCHASED_FULLFILLED'
export const UPDATE_PRODUCT_PURCHASED_PENDING = 'UPDATE_PRODUCT_PURCHASED_PENDING'
export const UPDATE_PRODUCT_PURCHASED_REJECTED = 'UPDATE_PRODUCT_PURCHASED_REJECTED'


//Types cart
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const UPDATE_PRODUCT_CART = 'UPDATE_PRODUCT_CART';
export const RESET_PRODUCT_CART = 'RESET_PRODUCT_CART';

